services:
    semaphore_db:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: semaphore
        volumes:
            - semaphore_postgres:/var/lib/postgresql/data
        networks:
            - semaphore_network
    semaphore:
        ports:
            - 59999:3000
        image: semaphoreui/semaphore:latest
        environment:
            SEMAPHORE_DB_DIALECT: postgres
            SEMAPHORE_DB_HOST: semaphore_db
            SEMAPHORE_DB_NAME: semaphore
            SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER}
            SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS}
            SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
            SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
            SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
            SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
        networks:
            - semaphore_network
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
    semaphore_postgres:
networks:
    semaphore_network: {driver: "bridge"}