services:
  lxconsole:
    image: penninglabs/lxconsole:latest
    volumes:
      - certs:/opt/lxconsole/certs
      - instance:/opt/lxconsole/instance
      - data:/data
      - config:/config
    ports:
      - ${LXCONSOLE_PORT}:5000
    restart: unless-stopped
    environment:
      - TZ=America/Edmonton

volumes:
  certs:
  instance:
  data:
  config:
