version: '3.8'

services:
  
  # Watchtower service that monitors and updates all containers.
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always  # Ensures the container is always running.
    ports:
      - "59000:8080"  # Maps port 59000 on the host to 8080 inside the container.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Provides access to the Docker daemon.
    environment:
      - WATCHTOWER_POLL_INTERVAL=10800  # 10,800 seconds (3 hours) polling interval.
      - WATCHTOWER_ROLLING_RESTART=true  # Enables rolling restarts to avoid downtime.
      - WATCHTOWER_MONITOR_ONLY=true  # Monitors containers but does not automatically update.
      - WATCHTOWER_LABEL_TAKE_PRECEDENCE=true  # Container-specific settings via labels take precedence.
      - WATCHTOWER_HTTP_API_TOKEN=b5e3abb8-fd7a-4db8-ba0c-182b409fad6c  # HTTP API token for secure communication.
    command: --debug --http-api-update  # Enables debug logging and the HTTP API for manual updates.

  # Watchtower service specifically for monitoring and updating the 'portainer' container.
  watchtower-portainer:
    container_name: watchtower-portainer
    image: containrrr/watchtower
    restart: always  # Ensures the container is always running.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Provides access to the Docker daemon.
    environment:
      - WATCHTOWER_POLL_INTERVAL=10800  # 10,800 seconds (3 hours) polling interval.
      - WATCHTOWER_ROLLING_RESTART=true  # Enables rolling restarts to avoid downtime.
    command: portainer --debug   # Limits monitoring and updating to the 'portainer' container only.