services:
  
  # Watchtower service that monitors and updates all containers.
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always  # Ensures the container is always running.
    ports:
      - "59000:8080"  # Maps port 59000 on the host to 8080 inside the container.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Provides access to the Docker daemon.
    environment:
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}  # Polling interval (seconds).
      - WATCHTOWER_MONITOR_ONLY=${WATCHTOWER_MONITOR_ONLY}  # Monitor without auto-updating.
      - WATCHTOWER_LABEL_TAKE_PRECEDENCE=${WATCHTOWER_LABEL_TAKE_PRECEDENCE}  # Label settings precedence.
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}  # Secure API token.
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=${WATCHTOWER_HTTP_API_PERIODIC_POLLS}  # Set automatic polling.
    command: --debug --http-api-update  # Enable debug logging and HTTP API for manual updates.

  # Watchtower service specifically for monitoring and updating the 'portainer' container.
  # watchtower-portainer:
  #   container_name: watchtower-portainer
  #   image: containrrr/watchtower
  #   restart: always  # Ensures the container is always running.
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock  # Provides access to the Docker daemon.
  #   environment:
  #     - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}  # Polling interval (seconds).
  #   command: portainer --debug   # Limits monitoring and updating to the 'portainer' container only.
