# Based on: https://github.com/TrafeX/docker-wordpress
# Execute WP-CLI commands: docker exec <container name> /usr/local/bin/wp --path=/usr/src/wordpress <command>
services:
  db:
    image: mariadb:11
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: ${DB_NAME}  
      MARIADB_USER: ${DB_USER}  
      MARIADB_PASSWORD: ${DB_PASSWORD}  
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    image: trafex/wordpress
    depends_on:
      - db
    build: ./
    volumes:
      - "site-data:/var/www/wp-content"
    ports:
      - ${PORT}:80
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}  
      DB_PASSWORD: ${DB_PASSWORD}  
      DB_NAME: ${DB_NAME} 
      WORDPRESS_SITE_URL: ${WP_SITE_URL}
      PHP_VALUE_upload_max_filesize: ${UPLOAD_MAX_FILESIZE}
      PHP_VALUE_post_max_size: ${POST_MAX_SIZE}
      PHP_VALUE_memory_limit: ${MEMORY_LIMIT}
      PHP_VALUE_max_execution_time: ${MAX_EXECUTION_TIME}
      PHP_VALUE_max_input_time: ${MAX_INPUT_TIME}
      FS_METHOD: direct
      # Debugging options:
      WP_DEBUG: ${WP_DEBUG}
      WP_DEBUG_DISPLAY: ${WP_DEBUG_DISPLAY}

volumes:
  db-data:
  site-data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.91.0/24
